create table scheduler_job_info ( 
	  job_id integer generated by default as identity
	, cron_expression varchar(255)
	, cron_job boolean
	, "desc" varchar(255)
	, interface_name varchar(255)
	, job_class varchar(255)
	, job_group varchar(255)
	, job_name varchar(255)
	, job_status varchar(255)
	, repeat_time bigint
	, primary key (job_id)
)