create table exchange_rate (
	  id bigint generated by default as identity
	, created_at timestamp
	, modified_at timestamp
	, base_currency varchar(10)
	, rate double
	, timestamp bigint
	, to_currency varchar(10)
	, primary key (id)
);

CREATE unique INDEX IF NOT EXISTS id_indx on exchange_rate (id);

CREATE unique INDEX IF NOT EXISTS from_to_indx on exchange_rate (base_currency,to_currency);
