
create table security_client (
  id bigint generated by default as identity
, clientid varchar(255)
, clientsecret varchar(255)
, name varchar(255)
, accountExpired boolean default false
, accountLocked boolean default false
, credentialsExpired boolean default false
, disabled boolean default false
, primary key (id));


CREATE unique INDEX IF NOT EXISTS id_indx on security_client (id);

CREATE unique INDEX IF NOT EXISTS client_id_indx on security_client (clientid);