INSERT INTO PERSON (EMAIL, NAME) VALUES ('vttanhua@icloud.com', 'Vesa');

INSERT INTO TODO (TITLE, DUE_DATE, STATUS, PRIORITY, OWNER_ID) VALUES ('Setup infrastructure in AWS', '2020-12-31', 'OPEN', 1, 1);
INSERT INTO TODO (TITLE, DUE_DATE, STATUS, PRIORITY, OWNER_ID) VALUES ('Secure application', '2020-12-31', 'OPEN', 1, 1);
INSERT INTO TODO (TITLE, DUE_DATE, STATUS, PRIORITY, OWNER_ID) VALUES ('Write book', '2020-12-31', 'OPEN', 1, 1);
INSERT INTO TODO (TITLE, DUE_DATE, STATUS, PRIORITY, OWNER_ID) VALUES ('Release it', '2020-12-31', 'OPEN', 1, 1);